language: python
sudo: true
dist: xenial

virtualenv:
  system_site_packages: false

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

before_install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

install:
  - sudo apt-get update -q
  - sudo apt-get install -y qemu-utils btrfs-tools

jobs:
  python:
    - "3.7-dev"
    - "3.8-dev"
    - "pypy3.5"


  include:
    - stage: "Tests: 3.4"
      name: "Unit Tests"
      python: "3.4"
      before_script:
        - pip install --upgrade pip
        - pip install -r requirements.txt
        - pip install -r requirements.tests.txt
        - pip install -e .
      script:
        - py.test --pep8 --cov=dregcli --cov-report=html -v --ignore dregcli/tests/tests_integration/
    - name: "Integration Tests"
      python: "3.4"
      before_script:
        - pip install --upgrade pip
        - pip install -r requirements.txt
        - pip install -r requirements.tests.txt
        - pip install -e .
      script:
        - dregcli/tests/tests_integration/start.sh

    - stage: "Tests: 3.5"
      name: "Unit Tests"
      python: "3.5"
      before_script:
        - pip install --upgrade pip
        - pip install -r requirements.txt
        - pip install -r requirements.tests.txt
        - pip install -e .
      script:
        - py.test --pep8 --cov=dregcli --cov-report=html -v --ignore dregcli/tests/tests_integration/

    - name: "Integration Tests"
      python: "3.5"
      script:
        - dregcli/tests/tests_integration/start.sh

    - stage: "Tests: 3.6"
      name: "Unit Tests"
      python: "3.6"
      before_script:
        - pip install --upgrade pip
        - pip install -r requirements.txt
        - pip install -r requirements.tests.txt
        - pip install -e .
      script:
        - py.test --pep8 --cov=dregcli --cov-report=html -v --ignore dregcli/tests/tests_integration/

    - name: "Integration Tests"
      python: "3.6"
      script:
        - dregcli/tests/tests_integration/start.sh

    - stage: "Tests: 3.7"
      name: "Unit Tests"
      python: "3.7"
      before_script:
        - pip install --upgrade pip
        - pip install -r requirements.txt
        - pip install -r requirements.tests.txt
        - pip install -e .
      script:
        - py.test --pep8 --cov=dregcli --cov-report=html -v --ignore dregcli/tests/tests_integration/

    - name: "Integration Tests"
      python: "3.7"
      script:
        - dregcli/tests/tests_integration/start.sh
